version: '3.3'

services:
  
  petshop-db:
    build:
      context: ..
      dockerfile: ./docker/db/Dockerfile

  petshop-web:
    build:
      context: ..
      dockerfile: ./docker/web/Dockerfile

  petshop-webservice:
    build:
      context: ..
      dockerfile: ./docker/webservice/Dockerfile